version: '3'

services:
  horse:
    image: hashload/delphi-dev:10.3.0-rio
    privileged: true
    tty: true
    ports:
      - '8080:8080'
      - '64211:64211'
    volumes:
      - ./emsserver.ini:/etc/ems/emsserver.ini